INSERT INTO `states` (`id`, `name`, `iso2`, `created_at`, `updated_at`)
VALUES  (1, 'Rio de Janeiro', 'RJ', NOW(), NOW()),
        (2, 'Minas Gerais', 'MG', NOW(), NOW()),
        (3, 'Amapá', 'AP', NOW(), NOW()),
        (4, 'Goiás', 'GO', NOW(), NOW()),
        (5, 'Rio Grande do Sul', 'RS', NOW(), NOW()),
        (6, 'Bahia', 'BA', NOW(), NOW()),
        (7, 'Sergipe', 'SE', NOW(), NOW()),
        (8, 'Amazonas', 'AM', NOW(), NOW()),
        (9, 'Paraíba', 'PB', NOW(), NOW()),
        (10, 'Pernambuco', 'PE', NOW(), NOW()),
        (11, 'Alagoas', 'AL', NOW(), NOW()),
        (12, 'Piauí', 'PI', NOW(), NOW()),
        (13, 'Pará', 'PA', NOW(), NOW()),
        (14, 'Mato Grosso do Sul', 'MS', NOW(), NOW()),
        (15, 'Mato Grosso', 'MT', NOW(), NOW()),
        (16, 'Acre', 'AC', NOW(), NOW()),
        (17, 'Rondônia', 'RO', NOW(), NOW()),
        (18, 'Santa Catarina', 'SC', NOW(), NOW()),
        (19, 'Maranhão', 'MA', NOW(), NOW()),
        (20, 'Ceará', 'CE', NOW(), NOW()),
        (21, 'Distrito Federal', 'DF', NOW(), NOW()),
        (22, 'Espírito Santo', 'ES', NOW(), NOW()),
        (23, 'Rio Grande do Norte', 'RN', NOW(), NOW()),
        (24, 'Tocantins', 'TO', NOW(), NOW()),
        (25, 'São Paulo', 'SP', NOW(), NOW()),
        (26, 'Paraná', 'PR', NOW(), NOW()),
        (27, 'Roraima', 'RR', NOW(), NOW());